---
title: Blair Rorani
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: blair@rorani.com
description: 'Designer of practical, visual, educational things. '
baseurl: 
url: http://blair.rorani.com
twitter_username: blairrorani
github_username: 
markdown: kramdown
ig_username: blairrorani
