---
title: Blairrorani.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Blair Rorani
description: I'm helping companies create change.
avatar: 
link-list:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: 
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
disqus: 
google_analytics: UA-18786151-1
url: http://blair.rorani.com
baseurl: ''
paginate: 1
paginate_path: "/:num/"
highlighter: rouge
permalink: "/:title/"
version: v1.0.0
sass:
  sass_dir: _scss
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
