---
title: Blair Rorani
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: blair@rorani.com
description: "\U0001F9E0 Blair makes things that help people get better at stuff"
baseurl: 
url: http://blair.rorani.com
twitter_username: blairrorani
github_username: 
markdown: kramdown
ig_username: blairrorani
