---
title: Blair Rorani
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: blair@rorani.com
description: Creator of practical, visual, educational content since 2002.
baseurl:
url: http://blair.rorani.com
twitter_usernamde: blairrorani
github_username:
markdown: kramdown
ig_username: blairrorani
